- src: 'https://github.com/MayNiklas/ansible-ssh.git'
  name: ansible-ssh
  scm: git
- src: 'https://github.com/MayNiklas/ansible-ssh-server.git'
  name: ansible-ssh-server
  scm: git
- src: 'https://github.com/MayNiklas/ansible-git.git'
  name: ansible-git
  scm: git
- src: 'https://github.com/MayNiklas/ansible-hostname.git'
  name: ansible-hostname
  scm: git
- src: 'https://github.com/MayNiklas/ansible-ufw.git'
  name: ansible-ufw
  scm: git
- src: 'https://github.com/MayNiklas/ansible-docker.git'
  name: ansible-docker
  scm: git