---

- hosts: all
  remote_user: "{{ login_user }}"
  vars_prompt:
   - name: "user_password"    
     prompt: "Enter a password for the user"    
     private: yes    
     encrypt: "md5_crypt"
     confirm: yes    
     salt_size: 7
  roles:
    - ansible-adduser
    
- hosts: all
  roles:
    - ansible-apt
    - ansible-ssh
    - ansible-ssh-server
    - ansible-git
    - ansible-hostname
    - ansible-ufw
    - ansible-docker
