---

- hosts: all
  remote_user: "{{ login_user }}"
  vars_prompt:
   - name: "user_password"    
     prompt: "Enter a password for the user"    
     private: yes    
     encrypt: "md5_crypt"
     confirm: yes    
     salt_size: 7
  roles:
    - ansible-adduser
    
- hosts: all
  roles:
    - ansible-apt
    - ansible-ssh-server
    - ansible-git
    - ansible-hostname
    # - ansible-ufw
    # - ansible-docker

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - ansible-k3s/common

- hosts: master
  become: yes
  roles:
    - ansible-k3s/master

- hosts: node
  become: yes
  roles:
    - ansible-k3s/node

